-- Courses: category for forms. One course can have many forms; one form can belong to many courses (many-to-many).
CREATE TABLE IF NOT EXISTS skyline_courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_skyline_courses_sort_order ON skyline_courses(sort_order);

-- Junction table: course <-> form (many-to-many)
CREATE TABLE IF NOT EXISTS skyline_course_forms (
  course_id BIGINT NOT NULL REFERENCES skyline_courses(id) ON DELETE CASCADE,
  form_id BIGINT NOT NULL REFERENCES skyline_forms(id) ON DELETE CASCADE,
  PRIMARY KEY (course_id, form_id)
);

CREATE INDEX IF NOT EXISTS idx_skyline_course_forms_form_id ON skyline_course_forms(form_id);
