-- Stores downloadable snapshots of "generic links" PDFs generated by admin.
CREATE TABLE IF NOT EXISTS skyline_course_link_exports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL REFERENCES skyline_courses(id) ON DELETE CASCADE,
  batch_id BIGINT REFERENCES skyline_batches(id) ON DELETE SET NULL,
  payload_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by BIGINT REFERENCES skyline_users(id)
);

CREATE INDEX IF NOT EXISTS idx_skyline_course_link_exports_course_id_created_at
  ON skyline_course_link_exports(course_id, created_at DESC);

