-- Role-specific secure links for instance access (student/trainer/office).
CREATE TABLE IF NOT EXISTS skyline_instance_access_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id BIGINT NOT NULL REFERENCES skyline_form_instances(id) ON DELETE CASCADE,
  role_context TEXT NOT NULL CHECK (role_context IN ('student', 'trainer', 'office')),
  token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  consumed_at TIMESTAMP WITH TIME ZONE,
  revoked_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_skyline_instance_access_tokens_instance_id
  ON skyline_instance_access_tokens(instance_id);

CREATE INDEX IF NOT EXISTS idx_skyline_instance_access_tokens_role_context
  ON skyline_instance_access_tokens(role_context);
