-- Trainer directory for future email/link-based assignment workflows.
CREATE TABLE IF NOT EXISTS skyline_trainers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_skyline_trainers_email ON skyline_trainers(email);
CREATE INDEX IF NOT EXISTS idx_skyline_trainers_status ON skyline_trainers(status);
